/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WineryWineryIdImport } from './routes/winery.$wineryId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WineryWineryIdRoute = WineryWineryIdImport.update({
  id: '/winery/$wineryId',
  path: '/winery/$wineryId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/winery/$wineryId': {
      id: '/winery/$wineryId'
      path: '/winery/$wineryId'
      fullPath: '/winery/$wineryId'
      preLoaderRoute: typeof WineryWineryIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/winery/$wineryId': typeof WineryWineryIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/winery/$wineryId': typeof WineryWineryIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/winery/$wineryId': typeof WineryWineryIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/winery/$wineryId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/winery/$wineryId'
  id: '__root__' | '/' | '/winery/$wineryId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WineryWineryIdRoute: typeof WineryWineryIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WineryWineryIdRoute: WineryWineryIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/winery/$wineryId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/winery/$wineryId": {
      "filePath": "winery.$wineryId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
