/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FirstRouteImport } from './routes/firstRoute'
import { Route as FirstRouteInnerRouteImport } from './routes/_firstRoute/innerRoute'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const FirstRouteRoute = FirstRouteImport.update({
  path: '/firstRoute',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const FirstRouteInnerRouteRoute = FirstRouteInnerRouteImport.update({
  path: '/innerRoute',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/firstRoute': {
      id: '/firstRoute'
      path: '/firstRoute'
      fullPath: '/firstRoute'
      preLoaderRoute: typeof FirstRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_firstRoute/innerRoute': {
      id: '/_firstRoute/innerRoute'
      path: '/innerRoute'
      fullPath: '/innerRoute'
      preLoaderRoute: typeof FirstRouteInnerRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  FirstRouteRoute,
  AboutLazyRoute,
  FirstRouteInnerRouteRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/firstRoute",
        "/about",
        "/_firstRoute/innerRoute"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/firstRoute": {
      "filePath": "firstRoute.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/_firstRoute/innerRoute": {
      "filePath": "_firstRoute/innerRoute.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
